server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          my-client:
            registration:
              client-id: "sgi"
              client-secret: "{noop}esunsecreto"
              client-authentication-methods: "client_secret_post"
              authorization-grant-types:  "client_credentials"
              scopes: "sgi:read"
